#### Data Cleaning

In [9]:
!pip3 install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (2.4.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-macosx_12_0_arm64.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 190.9 kB/s  0:00:54m0:00:0200:03
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp313-cp313-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 244.8 kB/s  0:01:20m0:00:0100:03
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [4]:
# importing dataset
df = pd.read_excel('customer_data.xlsx')
df.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [ ]:
# Identifying missing values
missing_value = df.isnull().sum()
print("Missing Values: ")
missing_value

Missing Values:

CustomerID                  0
Gender                      0
Age                         0
Income                      5
City                        3
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [10]:
# Handling Missing values
from sklearn.impute import SimpleImputer

# Handling missing values of Income
income = SimpleImputer(strategy = 'median')
income.fit(df[['Income']])
df[['Income']] = income.transform(df[['Income']])

# Handling missing values of City
city = SimpleImputer(strategy = 'most_frequent')
city.fit(df[['City']])
df[['City']] = city.transform(df[['City']])

In [11]:
# Identifying missing values
missing_value = df.isnull().sum()
print("Missing Values: ")
missing_value

Missing Values:

CustomerID                  0
Gender                      0
Age                         0
Income                      0
City                        0
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [12]:
# checking data types
df.dtypes

CustomerID                   object
Gender                       object
Age                           int64
Income                      float64
City                         object
Region                       object
Frequency_of_Purchases        int64
Average_Purchase_Amount     float64
Customer_Lifespan_Months     object
Purchase_Channel             object
Date_of_Purchase             object
Churn_Status                 object
dtype: object

In [15]:
# Checking invalid values
unique_values = df['Customer_Lifespan_Months'].unique()
print("Customer lifespan Months Values: ")
unique_values

Customer lifespan Months Values:

array([3, 4, 1, 2, 5, 'XXXX'], dtype=object)

In [16]:
# Removing Invalid Values
df = df[df['Customer_Lifespan_Months'] != 'XXXX']

In [17]:
# Checking invalid values
unique_values = df['Customer_Lifespan_Months'].unique()
print("Customer lifespan Months Values: ")
unique_values

Customer lifespan Months Values:

array([3, 4, 1, 2, 5], dtype=object)

In [18]:
# Converting Data Type to Integer
df['Customer_Lifespan_Months'] = df['Customer_Lifespan_Months'].astype(int)

/var/folders/rj/vl_rdlhj3bb37n47k8gqyhzw0000gn/T/ipykernel_6267/1438330483.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Customer_Lifespan_Months'] = df['Customer_Lifespan_Months'].astype(int)

In [20]:
# Converting Data Type to Datetime
df['Date_of_Purchase'] = pd.to_datetime(df['Date_of_Purchase'])

/var/folders/rj/vl_rdlhj3bb37n47k8gqyhzw0000gn/T/ipykernel_6267/3127089503.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date_of_Purchase'] = pd.to_datetime(df['Date_of_Purchase'])

In [21]:
# checking data types
df.dtypes

CustomerID                          object
Gender                              object
Age                                  int64
Income                             float64
City                                object
Region                              object
Frequency_of_Purchases               int64
Average_Purchase_Amount            float64
Customer_Lifespan_Months             int64
Purchase_Channel                    object
Date_of_Purchase            datetime64[ns]
Churn_Status                        object
dtype: object

In [ ]:
# Displaying dataset
df.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [ ]:
# Checking Duplicate Data
duplicates = df.duplicated()
df[duplicates]

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
80,C021,Female,22,41743.0,Los Angeles,Northeast,4,54.599,1,Online,2023-06-08,No

In [25]:
# Removing Duplicate Data
df.drop_duplicates(inplace = True)

In [26]:
# Checking Duplicate Data
duplicates = df.duplicated()
df[duplicates]

Empty DataFrame
Columns: [CustomerID, Gender, Age, Income, City, Region, Frequency_of_Purchases, Average_Purchase_Amount, Customer_Lifespan_Months, Purchase_Channel, Date_of_Purchase, Churn_Status]
Index: []